apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-helloworld
spec:
  selector:
    matchLabels:
      app: flask-helloworld
  template:
    metadata:
      labels:
        app: flask-helloworld
    spec:
      containers:
      - name: flask-helloworld
        image: flask-helloworld
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: FLASK_ENV
            value: development
        ports:
        - containerPort: 8080
